### ISSUE TITLE
DLDSR support

### ISSUE THREAD

**Issue by vaniron** [AipNooBest/wow-discord-rpc#1]
Addon stopped working (error about resolution) after trying to use it on 1080p monitor with fullscreen windowed mode and nvidia DLDSR on (1440p ingame). Is there any chance to make it work with upscaled resolution?

More info here: https://www.tomshardware.com/news/nvidia-dldsr-deep-learning-dynamic-super-resolution

**Comment by AipNooBest** [comment]
Unfortunately, I don't have an RTX GPU, so I can't check it myself. What is the exact error addon providing? Could you attach a screenshot or error log?

**Comment by vaniron** [comment]
![image](https://user-images.githubusercontent.com/17107410/151375330-84a2f598-01e0-4a36-ad90-af13475a3045.png)


and these in the log:
ERROR:root:Error decoding the pixels: 'utf-8' codec can't decode byte 0xcd in position 27: invalid continuation byte.
ERROR:root:Error decoding the pixels: 'utf-8' codec can't decode byte 0x91 in position 27: invalid start byte.

**Comment by AipNooBest** [comment]
Does the colored array of pixels appear in the game? If so, could you please provide a screenshot of it?

**Comment by vaniron** [comment]
its basically invisible
![image](https://user-images.githubusercontent.com/17107410/151574540-77be3448-53bc-4824-b711-5a04728bb03e.png)

![image](https://user-images.githubusercontent.com/17107410/151574704-6021d69e-179f-4439-aaaa-a3ce4f239317.png)

**Comment by AipNooBest** [comment]
Ok, the addon itself is indeed working. But looks like resizing it somehow messes up colors, so the script cannot decode it. Maybe scaling these pixels up from 1x1 will fix the issue, let me check it

**Comment by AipNooBest** [comment]
Yeah, turns out that exactly is the problem - colors are changed a bit because of resizing. I edited script and addon, so you can try to adjust pixels size, however I cannot guarantee this to work. I could simulate this by changing Window's overall scaling(in display settings), and there's a general problem with scaling, which in theory can be solved by increasing squares' size and picking color at the center of them, but that requires more time to code

**Comment by vaniron** [comment]
What values should I set when using 2880x1620 on 1920x1080? I tried 1.5 and 0.667 on both but neither is working.

**Comment by AipNooBest** [comment]
At least 2x2 - the bigger pixels are, the more clear they are. However, if you will make them too big, they just won't fit on screen, so values like 6x6 probably won't work, but you can try. And yeah, they look a bit ugly when they're big, that's why I initially made them almost invisible, however that's the only choice for now

**Comment by vaniron** [comment]
Its working fine with 4x4 pixels so thanks for your help!

**Comment by AipNooBest** [comment]
Glad that helped you!
Probably I'll rewrite the script a bit to fix the general problem with scaling(which blurs these pixels), but I doubt it will be soon
